### ISSUE TITLE
Using Postgresql as Database Engine

### ISSUE THREAD

**Issue by wilson-ng** [monitoringartist/jasperserver-xxl#15]
Hai, 

I'm start using this Dockerized JasperServer, when configure environment variable for `JS_DB_TYPE` with value `postgres` (as mention in configuration section), and then fire up the container, got `cp sample_conf/postgres_master.properties default_master.properties`.

After look awhile at `entrypoin.sh` on this github, found on line 7, expect `JS_DB_TYPE` fill with `postgresql` value, so the copy form format expected like this `cp sample_conf/postgresql_master.properties default_master.properties`.

Because of that, change value `JS_DB_TYPE` to `postgresql`, seems back to work.

Maybe this issue can open for change default configuration of `JS_DB_TYPE` from `postgres` to `postgresql`, or change `entrypoint.sh`.

**Comment by jangaraj** [comment]
Please use official project https://github.com/TIBCOSoftware/js-docker. This project is deprecated.
