### ISSUE TITLE
overriding the smpt password with smtp username in entrypoint.sh file.

### ISSUE THREAD

**Issue by irparajababu** [monitoringartist/jasperserver-xxl#17]
It seems below line is overriding the password with username.
s|^# quartz\.mail\.sender\.password.*$|quartz.mail.sender.username = $JS_MAIL_PASSWORD|g;

**Comment by jangaraj** [comment]
You are right. Unfortunately, this project is not maintained anymore. I recommend to use https://github.com/TIBCOSoftware/js-docker as a base.
