### ISSUE TITLE
Could not connect to jasper.db:3306 

### ISSUE THREAD

**Issue by FatmaBouchekoi** [monitoringartist/jasperserver-xxl#5]
When I execute 
`docker-compose up`
I get this error :
`/jasperserver/buildomatic/bin/app-server.xml:60: java.sql.SQLNonTransientConnectionException: Could not connect to jasper.db:3306 : Connection refused`

**Comment by jangaraj** [comment]
Probably jasperserver has started before DB. Kill server and try it again.

**Comment by jangaraj** [comment]
Closing - no more details from the user.
